### ISSUE TITLE
How to output ASCII instead of Hexadecimal

### ISSUE THREAD

**Issue by shillshocked** [thephoeron/cl-isaac#2]
Alright, I got a rudimentary password generator for 256 AES keys. It involves a quick bash script calling a .lisp file. 

Here is the bash script:

```
#!/bin/bash
#sbcl options are to suppress output in order to just use script results, and quit after it's done
sbcl --noinform --noprint --disable-debugger --non-interactive --quit --load ~/scripts/passgen.lisp
```

Here is the lisp script:

```
;; suppress unnecessary output
(let* ((*standard-output* (make-broadcast-stream)) (*error-output* *standard-output*))
    (ql:quickload "cl-isaac"))

;; suppress unnecessary output
(let* ((*standard-output* (make-broadcast-stream)) (*error-output* *standard-output*))
    (defvar self-ctx (isaac:init-self-seed :count 3 :is64 t)))

(format t "~64,'0x" (isaac:rand-bits-64 self-ctx 256))
```

cl-isaac outputs in Hex (0x). How can I get the characters to come out as ASCII that includes lowercase letters, uppercase letters, symbol and numbers that you can type in as password characters?

**Comment by thephoeron** [comment]
It's actually the format string that is outputting hexadecimal&mdash;the call to `(isaac:rand-bits-64 ...)` returns a random integer.  Using one of my other libraries, `bit-smasher` (also in quicklisp), you can get the octet-vector for the random integer instead of using `format` to set it as hex, and then use `flexi-streams` to get a string representation of the octets.  You can try something to this effect:

``` lisp
(ql:quickload '("cl-isaac" "bit-smasher" "flexi-streams"))

(defvar self-ctx (isaac:init-self-seed :count 3 :is64 t))

(princ (flexi-streams:octets-to-string (bit-smasher:octets<- (isaac:rand-bits-64 self-ctx 256))))
```

If you want to restrict the strings to alphanumeric characters, you can play around with modular arithmetic too. Or `loop` and `code-char`. Or the `cl-base64` and `cl-base58` libraries.  You have a lot of options.
